# Generated by Django 5.0.7 on 2024-09-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="status",
            field=models.CharField(
                default="Ожидает модерации", max_length=100, verbose_name="Статус"
            ),
        ),
    ]
