# Generated by Django 5.1.4 on 2024-12-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0007_photo_name_photo_prev_description_photo_prev_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="prev_name",
            field=models.CharField(
                max_length=127, null=True, verbose_name="Предыдущее название"
            ),
        ),
    ]
